
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    restart: always
    env_file:
      - .env

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 初期化SQL
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: