#NOTES
## 1.docker build -f Dockerfile.timer -t timer . でイメージを作成する
#### buildの-fオプションはDockerfileの格納パスを指定する（オプション）
#### buildの-tオプションはイメージ名を指定する（オプション）

## 1.5 今の古いコンテナを消す docker rm -f timer

## 2.docker imagesでイメージが作成されたかを確認

## 3.docker create --env-file .env -v $(pwd):/app --name timer timer でイメージからコンテナの状態にする
#### createの--nameオプションはコンテナ名を指定する（オプション）

## 4.docker ps -aで作成したコンテナを確認
#### psの-aオプションはコンテナをすべて表示する（オプション）

## 5.docker start timer でコンテナを起動


### docker runの--env-fileで環境変数を渡せる

# docker build --platform linux/amd64 -f Dockerfile.timer -t sottorabin/discord_timer .
# docker push sottorabin/discord_timer:latest

FROM python:3.13-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV TZ=Asia/Tokyo

# ffmpegをインストール
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# requirements.txtをコピーしてパッケージをインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# timer.pyと、timer.pyからインポートされているschemas.pyをコンテナにコピー
COPY ./timer .

# コンテナ起動時にtimer.pyを実行
CMD ["python3", "main.py"]
